### Introspection for opaque tokens
POST http://localhost:9500/oauth2/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientid}} {{clientsecret}}

token={{$auth.token("spring")}}
###